export type OrganisationRowType = {
  created_at: string | null;
  id: string;
  name: string;
  reps?: Record<string, any>[] | null;
  updated_at: string | null;
};
export type OrganisationInsertType = {
  created_at?: string | null;
  id?: string;
  name: string;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};
export type OrganisationUpdateType = {
  created_at?: string | null;
  id?: string;
  name?: string;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};

export type DivisionRowType = {
  created_at: string | null;
  id: string;
  name: string;
  organisation_id: string | null;
  reps?: Record<string, any>[] | null;
  updated_at: string | null;
};
export type DivisionInsertType = {
  created_at?: string | null;
  id?: string;
  name: string;
  organisation_id?: string | null;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};
export type DivisionUpdateType = {
  created_at?: string | null;
  id?: string;
  name?: string;
  organisation_id?: string | null;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};

export type RegionRowType = {
  created_at?: string | null;
  division_id?: string | null;
  id?: string;
  name?: string;
  organisation_id?: string | null;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};

export type ChapterRowType = {
  base_currency: string | null;
  country: string | null;
  created_at: string | null;
  division_id: string | null;
  id: string;
  name: string;
  organisation_id: string | null;
  region_id: string | null;
  reps?: Record<string, any>[] | null;
  updated_at: string | null;
};
export type ChapterInsertType = {
  base_currency?: string | null;
  country?: string | null;
  created_at?: string | null;
  division_id?: string | null;
  id?: string;
  name: string;
  organisation_id?: string | null;
  region_id?: string | null;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};
export type ChapterUpdateType = {
  base_currency?: string | null;
  country?: string | null;
  created_at?: string | null;
  division_id?: string | null;
  id?: string;
  name?: string;
  organisation_id?: string | null;
  region_id?: string | null;
  reps?: Record<string, any>[] | null;
  updated_at?: string | null;
};

export type PartnerRowType = {
  g20_active: boolean | null;
  proposed_payment_scheduled: boolean | null;
  married: boolean | null;
  voluntary_participation: boolean | null;
  attestation: boolean | null;
  marriage_anniversary: string | null;
  g20_category: string | null;
  g20_amount: number | null;
  motivation: string | null;
  address: string | null;
  birth_day_mmdd: string | null;
  chapter_id: string | null;
  cognito_user_id: string | null;
  created_at: string | null;
  date_of_birth: string | null;
  division_id: string | null;
  email: string;
  first_name: string;
  gender: string | null;
  ggp_category: string;
  id: string;
  image_url: string | null;
  last_name: string;
  middle_name: string | null;
  name: string | null;
  name_code: string | null;
  nationality: string | null;
  occupation: string | null;
  organisation_id: string | null;
  partner_type: string | null;
  paystack_authorization_code: string | null;
  paystack_authorization_details: Record<string, any> | null;
  paystack_customer_code: string | null;
  paystack_customer_id: string | null;
  paystack_monthly_payment: boolean | null;
  paystack_monthly_payment_id: string | null;
  permission_access: string[] | null;
  permission_type: string | null;
  phone_number: string | null;
  region_id: string | null;
  remission_start_date: string | null;
  status: string | null;
  stripe_customer_id: string | null;
  g20_subscription_ids: Record<string, any>[] | null;
  g20_paystack_customer_code: string | null;
  g20_paystack_customer_id: string | null;
  g20_paystack_authorization_code: string | null;
  g20_paystack_authorization_details: Record<string, any> | null;
  subscription_ids: string[] | null;
  unique_code: string | null;
  updated_at: string | null;
  verified: boolean;
  assistant: boolean;
};
export type PartnerInsertType = {
  g20_active?: boolean | null;
  proposed_payment_scheduled?: boolean | null;
  married?: boolean | null;
  voluntary_participation?: boolean | null;
  attestation?: boolean | null;
  marriage_anniversary?: string | null;
  g20_category?: string | null;
  g20_amount?: number | null;
  motivation?: string | null;
  address?: string | null;
  birth_day_mmdd?: string | null;
  chapter_id?: string | null;
  cognito_user_id?: string | null;
  created_at?: string | null;
  date_of_birth?: string | null;
  division_id?: string | null;
  email: string;
  first_name: string;
  gender?: string | null;
  ggp_category: string;
  id?: string;
  image_url?: string | null;
  last_name: string;
  middle_name?: string | null;
  name?: string | null;
  name_code?: string | null;
  nationality?: string | null;
  occupation?: string | null;
  organisation_id?: string | null;
  partner_type?: string | null;
  paystack_authorization_code?: string | null;
  paystack_authorization_details?: Record<string, any> | null;
  paystack_customer_code?: string | null;
  paystack_customer_id?: string | null;
  paystack_monthly_payment?: boolean | null;
  paystack_monthly_payment_id?: string | null;
  permission_access?: string[] | null;
  permission_type?: string | null;
  phone_number?: string | null;
  region_id?: string | null;
  remission_start_date?: string | null;
  status?: string | null;
  stripe_customer_id?: string | null;
  g20_subscription_ids?: Record<string, any>[] | null;
  g20_paystack_customer_code?: string | null;
  g20_paystack_customer_id?: string | null;
  g20_paystack_authorization_code?: string | null;
  g20_paystack_authorization_details?: Record<string, any> | null;
  subscription_ids?: string[] | null;
  unique_code?: string | null;
  updated_at?: string | null;
  verified?: boolean;
  assistant?: boolean;
};
export type PartnerUpdateType = {
  g20_active?: boolean | null;
  proposed_payment_scheduled?: boolean | null;
  married?: boolean | null;
  voluntary_participation?: boolean | null;
  attestation?: boolean | null;
  marriage_anniversary?: string | null;
  g20_category?: string | null;
  g20_amount?: number | null;
  motivation?: string | null;
  address?: string | null;
  birth_day_mmdd?: string | null;
  chapter_id?: string | null;
  cognito_user_id?: string | null;
  created_at?: string | null;
  date_of_birth?: string | null;
  division_id?: string | null;
  email?: string;
  first_name?: string;
  gender?: string | null;
  ggp_category?: string;
  id?: string;
  image_url?: string | null;
  last_name?: string;
  middle_name?: string | null;
  name?: string | null;
  name_code?: string | null;
  nationality?: string | null;
  occupation?: string | null;
  organisation_id?: string | null;
  partner_type?: string | null;
  paystack_authorization_code?: string | null;
  paystack_authorization_details?: Record<string, any> | null;
  paystack_customer_code?: string | null;
  paystack_customer_id?: string | null;
  paystack_monthly_payment?: boolean | null;
  paystack_monthly_payment_id?: string | null;
  permission_access?: string[] | null;
  permission_type?: string | null;
  phone_number?: string | null;
  region_id?: string | null;
  remission_start_date?: string | null;
  status?: string | null;
  stripe_customer_id?: string | null;
  g20_subscription_ids?: Record<string, any>[] | null;
  g20_paystack_customer_code?: string | null;
  g20_paystack_customer_id?: string | null;
  g20_paystack_authorization_code?: string | null;
  g20_paystack_authorization_details?: Record<string, any> | null;
  subscription_ids?: string[] | null;
  unique_code?: string | null;
  updated_at?: string | null;
  verified?: boolean;
  assistant?: boolean;
};

// updated
export type PaymentRowType = {
  amount: number | null;
  approved_by: string | null;
  approved_by_id: string | null;
  approved_by_image: string | null;
  chapter_id: string | null;
  conversion_amount: number | null;
  conversion_currency: string | null;
  conversion_description: string | null;
  conversion_rate: number | null;
  conversion_time: string | null;
  created_at: string | null;
  currency: string | null;
  description: string | null;
  division_id: string | null;
  gbp_equivalent: number | null;
  id: string;
  is_converted: boolean | null;
  organisation_id: string | null;
  payment_date: string | null;
  recurring_id: string | null;
  region_id: string | null;
  remission_month: string | null;
  remission_period: string | null;
  remission_year: string | null;
  status: string | null;
  unique_code: string | null;
  updated_at: string | null;
  user_id: string | null;
  user_name: string | null;
};

export type PaymentInsertType = {
  amount?: number | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  chapter_id?: string | null;
  conversion_amount?: number | null;
  conversion_currency?: string | null;
  conversion_description?: string | null;
  conversion_rate?: number | null;
  conversion_time?: string | null;
  created_at?: string | null;
  currency?: string | null;
  description?: string | null;
  division_id?: string | null;
  gbp_equivalent?: number | null;
  id?: string;
  is_converted?: boolean | null;
  organisation_id?: string | null;
  payment_date?: string | null;
  recurring_id?: string | null;
  region_id?: string | null;
  remission_month?: string | null;
  remission_period?: string | null;
  remission_year?: string | null;
  status?: string | null;
  updated_at?: string | null;
  unique_code?: string | null;
  user_id?: string | null;
  user_name?: string | null;
};
export type PaymentUpdateType = {
  amount?: number | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  chapter_id?: string | null;
  conversion_amount?: number | null;
  conversion_currency?: string | null;
  conversion_description?: string | null;
  conversion_rate?: number | null;
  conversion_time?: string | null;
  created_at?: string | null;
  currency?: string | null;
  description?: string | null;
  division_id?: string | null;
  gbp_equivalent?: number | null;
  id?: string;
  is_converted?: boolean | null;
  organisation_id?: string | null;
  payment_date?: string | null;
  recurring_id?: string | null;
  region_id?: string | null;
  remission_month?: string | null;
  remission_period?: string | null;
  remission_year?: string | null;
  status?: string | null;
  unique_code?: string | null;
  updated_at?: string | null;
  user_id?: string | null;
  user_name?: string | null;
};

export type G20PaymentRowType = {
  id: string;
  created_at: string | null;
  updated_at: string | null;
  user_id: string;
  organisation_id: string | null;
  division_id: string | null;
  chapter_id: string | null;
  unique_code: string | null;
  email: string;
  first_name: string;
  last_name: string;
  payment_date: string;
  amount: number;
  currency: string;
  status: string;
  payment_channel: string | null;
  payment_method: string | null;
  payment_reference: string | null;
  receipt_url: string | null;
  proof_file_path: string | null;
  description: string | null;
  metadata: Record<string, any> | null;
  approved_by: string | null;
  approved_by_id: string | null;
  approved_by_image: string | null;
  recorded_by: string | null;
  recorded_by_id: string | null;
};

export type G20PaymentInsertType = {
  id?: string;
  created_at?: string | null;
  updated_at?: string | null;
  user_id: string;
  organisation_id?: string | null;
  division_id?: string | null;
  chapter_id?: string | null;
  unique_code?: string | null;
  email: string;
  first_name: string;
  last_name: string;
  payment_date: string;
  amount: number;
  currency?: string;
  status?: string;
  payment_channel?: string | null;
  payment_method?: string | null;
  payment_reference?: string | null;
  receipt_url?: string | null;
  proof_file_path?: string | null;
  description?: string | null;
  metadata?: Record<string, any> | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  recorded_by?: string | null;
  recorded_by_id?: string | null;
};

export type G20PaymentUpdateType = {
  id?: string;
  created_at?: string | null;
  updated_at?: string | null;
  user_id?: string;
  organisation_id?: string | null;
  division_id?: string | null;
  chapter_id?: string | null;
  unique_code?: string | null;
  email?: string;
  first_name?: string;
  last_name?: string;
  payment_date?: string;
  amount?: number;
  currency?: string;
  status?: string;
  payment_channel?: string | null;
  payment_method?: string | null;
  payment_reference?: string | null;
  receipt_url?: string | null;
  proof_file_path?: string | null;
  description?: string | null;
  metadata?: Record<string, any> | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  recorded_by?: string | null;
  recorded_by_id?: string | null;
};

export type PaystactRecurringPaymentsRowType = {
  active: boolean | null;
  amount: number | null;
  authorization_code: string;
  chapter_id: string | null;
  charge_day: number | null;
  created_at: string | null;
  currency: string | null;
  customer_code: string | null;
  email: string;
  frequency: string | null;
  id: string;
  updated_at: string | null;
  user_id: string | null;
};
export type PaystactRecurringPaymentsInsertType = {
  active?: boolean | null;
  amount?: number | null;
  authorization_code: string;
  chapter_id?: string | null;
  charge_day?: number | null;
  created_at?: string | null;
  currency?: string | null;
  customer_code?: string | null;
  email: string;
  frequency?: string | null;
  id?: string;
  updated_at?: string | null;
  user_id?: string | null;
};
export type PaystactRecurringPaymentsUpdateType = {
  active?: boolean | null;
  amount?: number | null;
  authorization_code?: string;
  chapter_id?: string | null;
  charge_day?: number | null;
  created_at?: string | null;
  currency?: string | null;
  customer_code?: string | null;
  email?: string;
  frequency?: string | null;
  id?: string;
  updated_at?: string | null;
  user_id?: string | null;
};

export type PaystactPendingPaymentsRowType = {
  amount: number | null;
  approved_by: string | null;
  approved_by_id: string | null;
  approved_by_image: string | null;
  authorization_code: string | null;
  chapter_id: string | null;
  created_at: string | null;
  currency: string | null;
  customer_code: string | null;
  description: string | null;
  division_id: string | null;
  id: string;
  organisation_id: string | null;
  payment_date: string | null;
  recurring_id: string | null;
  region_id: string | null;
  remission_month: string | null;
  remission_period: string | null;
  remission_year: string | null;
  status: string | null;
  unique_code: string | null;
  updated_at: string | null;
  user_id: string | null;
  user_name: string | null;
};
export type PaystactPendingPaymentsInsertType = {
  amount?: number | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  authorization_code?: string | null;
  chapter_id?: string | null;
  created_at?: string | null;
  currency?: string | null;
  customer_code?: string | null;
  description?: string | null;
  division_id?: string | null;
  id?: string;
  organisation_id?: string | null;
  payment_date?: string | null;
  recurring_id?: string | null;
  region_id?: string | null;
  remission_month?: string | null;
  remission_period?: string | null;
  remission_year?: string | null;
  status?: string | null;
  unique_code?: string | null;
  updated_at?: string | null;
  user_id?: string | null;
  user_name?: string | null;
};
export type PaystactPendingPaymentsUpdateType = {
  amount?: number | null;
  approved_by?: string | null;
  approved_by_id?: string | null;
  approved_by_image?: string | null;
  authorization_code?: string | null;
  chapter_id?: string | null;
  created_at?: string | null;
  currency?: string | null;
  customer_code?: string | null;
  description?: string | null;
  division_id?: string | null;
  id?: string;
  organisation_id?: string | null;
  payment_date?: string | null;
  recurring_id?: string | null;
  region_id?: string | null;
  remission_month?: string | null;
  remission_period?: string | null;
  remission_year?: string | null;
  status?: string | null;
  unique_code?: string | null;
  updated_at?: string | null;
  user_id?: string | null;
  user_name?: string | null;
};

export type ProposedPaymentScheduleRowType = {
  id: string;
  created_at: string;
  user_id: string;
  schedule_year: number;
  schedule_index: number;
  proposed_amount: number;
  proposed_date: string;
  unique_code: string | null;
  organisation_id: string | null;
  division_id: string | null;
  chapter_id: string | null;
  email: string;
  first_name: string;
  last_name: string;
  status: "pending" | "missed" | "cleared";
};

export type ProposedPaymentScheduleInsertType = {
  id?: string;
  created_at?: string;
  user_id: string;
  schedule_year: number;
  schedule_index: number;
  proposed_amount: number;
  proposed_date: string;
  unique_code?: string | null;
  organisation_id?: string | null;
  division_id?: string | null;
  chapter_id?: string | null;
  email: string;
  first_name: string;
  last_name: string;
  status?: "pending" | "missed" | "cleared";
};

